# Generated by Django 4.2.4 on 2023-08-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Pelicula',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='pelicula',
        ),
    ]
