# Generated by Django 4.2.4 on 2023-08-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ventas_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='fecha',
        ),
    ]
