# Generated by Django 4.2.4 on 2023-08-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_ventas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='entrada2x1',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='numeroEntradas',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='pelicula',
        ),
    ]
